import {
    BadRequestException,
    ConflictException,
    Injectable,
    NotFoundException,
} from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { ClientSession, Model, Types } from 'mongoose';
import { v4 as uuidv4 } from 'uuid';
import { CreateReferralDto } from '../dto/create-referral.dto';
import {
    Referral,
    ReferralDocument,
    ReferralType,
} from '../schemas/referral.schema';
import {
    ReferralUsage,
    ReferralUsageDocument,
} from '../schemas/referral-usage.schema';
import { UserNS } from 'src/users/schemas/user.schema';
import { stringToObjectId } from 'src/utils/db.utils';

@Injectable()
export class ReferenceSystemService {
    constructor(
        @InjectModel(Referral.name)
        private referralModel: Model<ReferralDocument>,
        @InjectModel(ReferralUsage.name)
        private referralUsageModel: Model<ReferralUsageDocument>,
    ) { }

    /**
     * Generates a unique random referral code using UUID
     * The code is generated by taking the first 8 characters of a UUID (without hyphens)
     * @returns A unique 8-character referral code
     */
    private async generateUniqueReferralCode(): Promise<string> {
        let code: string;
        let isUnique = false;
        let attempts = 0;
        const maxAttempts = 10; // Prevent infinite loop

        // Keep generating until we find a unique code
        while (!isUnique && attempts < maxAttempts) {
            // Generate UUID and remove hyphens, then take first 8 characters
            code = uuidv4().replace(/-/g, '').substring(0, 8).toLowerCase();

            // Check if code already exists
            const existingReferral = await this.referralModel.findOne({
                code,
            });

            if (!existingReferral) {
                isUnique = true;
            } else {
                attempts++;
            }
        }

        if (!isUnique) {
            throw new BadRequestException(
                'Failed to generate a unique referral code. Please try again or provide a custom code.',
            );
        }

        return code;
    }

    /**
     * Creates a new referral code
     * @param createReferralDto - DTO containing optional code, title, and type
     * @param ownerId - User ID of the creator (from authenticated token)
     * @returns Created referral document
     */
    async createReferral(
        createReferralDto: CreateReferralDto,
        ownerId: string,
    ): Promise<ReferralDocument> {
        // Validate ownerId
        if (!Types.ObjectId.isValid(ownerId)) {
            throw new BadRequestException(`Invalid owner ID: ${ownerId}`);
        }

        // Generate code if not provided
        let referralCode = createReferralDto.code;
        if (!referralCode) {
            referralCode = await this.generateUniqueReferralCode();
        }

        // Check if code already exists (in case user provided one)
        const existingReferral = await this.referralModel.findOne({
            code: referralCode,
        });

        if (existingReferral) {
            throw new ConflictException(
                `Referral code '${referralCode}' already exists`,
            );
        }

        // Check if title already exists
        const existingTitle = await this.referralModel.findOne({
            title: createReferralDto.title,
        });

        if (existingTitle) {
            throw new ConflictException(
                `Referral title '${createReferralDto.title}' already exists`,
            );
        }

        // Create new referral
        const newReferral = new this.referralModel({
            code: referralCode,
            title: createReferralDto.title,
            type: createReferralDto.type,
            owner_id: new Types.ObjectId(ownerId),
        });

        return await newReferral.save();
    }

    /**
     * Finds a referral by code
     * @param code - Referral code to search for
     * @returns Referral document if found
     * @throws NotFoundException if referral not found
     */
    async findReferralByCode(
        code: string,
        session?: ClientSession,
    ): Promise<ReferralDocument> {
        const query = this.referralModel.findOne({ code });
        if (session) {
            query.session(session);
        }
        const referral = await query.lean().exec();

        if (!referral) {
            throw new NotFoundException(`Referral code '${code}' not found`);
        }

        return referral;
    }

    /**
     * Records a referral usage when a user signs up with an invitation code
     * @param referralId - ID of the referral that was used
     * @param consumerId - ID of the user who used the referral
     * @returns Created referral usage document
     */
    private async recordReferralUsage(
        referralId: Types.ObjectId,
        consumerId: Types.ObjectId,
        session?: ClientSession,
    ): Promise<ReferralUsageDocument> {

        const referralQuery = this.referralModel.findById(referralId);
        if (session) referralQuery.session(session);

        const referral = await referralQuery.exec();
        // Check if referral exists *
        if (!referral) {
            throw new NotFoundException(`Referral with ID ${referralId} not found`);
        }

        // for promo (future use)
        // Check if this consumer has already used this referral
        const existingUsageQuery = this.referralUsageModel.findOne({
            referral_id: referralId,
            consumer_id: consumerId,
        });
        if (session) {
            existingUsageQuery.session(session);
        }
        const existingUsage = await existingUsageQuery.exec();

        if (existingUsage) {
            throw new ConflictException(
                'This referral code has already been used by this user',
            );
        }

        // Create referral usage record
        const newReferralUsage = new this.referralUsageModel({
            referral_id: referralId,
            consumer_id: consumerId,
            consumer_type: 'user',
        });

        return await newReferralUsage.save({ session });
    }

    /**
     * Gets all referrals created by a specific owner
     * @param ownerId - User ID of the owner
     * @returns Array of referral documents
     */
    async getReferralsByOwner(ownerId: string): Promise<ReferralDocument[]> {
        if (!Types.ObjectId.isValid(ownerId)) {
            throw new BadRequestException(`Invalid owner ID: ${ownerId}`);
        }

        return await this.referralModel
            .find({ owner_id: new Types.ObjectId(ownerId) })
            .exec();
    }

    /**
     * Handles referral logic when a user signs up with discovery_info
     * This method should be called after user creation is successful
     * @param userId - ID of the newly created user
     * @param discoveryInfo - Discovery info containing discovery_mode and optional invitation_code
     * @returns Referral usage document if invitation code was used, null otherwise
     * @throws NotFoundException if invitation code is invalid
     * @throws ConflictException if referral code has already been used by this user
     */
    async handleReferralOnSignup(
        userId: string,
        invitation_code: string,
        session?: ClientSession,
    ): Promise<ReferralUsageDocument | null> {

        // Find referral by code
        const referral = await this.findReferralByCode(
            invitation_code,
            session,
        );

        // Record referral usage
        return await this.recordReferralUsage(
            referral._id,
            stringToObjectId(userId),
            session,
        );
    }
}

