export enum AUTH_ERROR_CODE {
  TOKEN_NOT_FOUND = 'TOKEN_NOT_FOUND',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_MALFORMED = 'TOKEN_MALFORMED',
  TOKEN_INVALID_SIGNATURE = 'TOKEN_INVALID_SIGNATURE',
}
