export const pakistanDistricts = {
  punjab: [
    { value: 'attock', label: 'Attock' },
    { value: 'bahawalnagar', label: 'Bahawalnagar' },
    { value: 'bahawalpur', label: 'Bahawalpur' },
    { value: 'bhakkar', label: 'Bhakkar' },
    { value: 'chakwal', label: 'Chakwal' },
    { value: 'chiniot', label: 'Chiniot' },
    { value: 'dera-ghazi-khan', label: 'Dera Ghazi Khan' },
    { value: 'faisalabad', label: 'Faisalabad' },
    { value: 'gujranwala', label: 'Gujranwala' },
    { value: 'gujrat', label: 'Gujrat' },
    { value: 'hafizabad', label: 'Hafizabad' },
    { value: 'jhang', label: 'Jhang' },
    { value: 'jhelum', label: 'Jhelum' },
    { value: 'kasur', label: 'Kasur' },
    { value: 'khanewal', label: 'Khanewal' },
    { value: 'khushab', label: 'Khushab' },
    { value: 'lahore', label: 'Lahore' },
    { value: 'layyah', label: 'Layyah' },
    { value: 'lodhran', label: 'Lodhran' },
    { value: 'mandi-bahauddin', label: 'Mandi Bahauddin' },
    { value: 'mianwali', label: 'Mianwali' },
    { value: 'multan', label: 'Multan' },
    { value: 'muzaffargarh', label: 'Muzaffargarh' },
    { value: 'narowal', label: 'Narowal' },
    { value: 'nankana-sahib', label: 'Nankana Sahib' },
    { value: 'okara', label: 'Okara' },
    { value: 'pakpattan', label: 'Pakpattan' },
    { value: 'rahim-yar-khan', label: 'Rahim Yar Khan' },
    { value: 'rajanpur', label: 'Rajanpur' },
    { value: 'rawalpindi', label: 'Rawalpindi' },
    { value: 'sahiwal', label: 'Sahiwal' },
    { value: 'sargodha', label: 'Sargodha' },
    { value: 'sheikhupura', label: 'Sheikhupura' },
    { value: 'sialkot', label: 'Sialkot' },
    { value: 'toba-tek-singh', label: 'Toba Tek Singh' },
    { value: 'vehari', label: 'Vehari' }
  ],
  sindh: [
    { value: 'badin', label: 'Badin' },
    { value: 'dadu', label: 'Dadu' },
    { value: 'ghotki', label: 'Ghotki' },
    { value: 'hyderabad', label: 'Hyderabad' },
    { value: 'jacobabad', label: 'Jacobabad' },
    { value: 'jamshoro', label: 'Jamshoro' },
    { value: 'karachi-central', label: 'Karachi Central' },
    { value: 'karachi-east', label: 'Karachi East' },
    { value: 'karachi-south', label: 'Karachi South' },
    { value: 'karachi-west', label: 'Karachi West' },
    { value: 'karachi-malir', label: 'Karachi Malir' },
    { value: 'karachi-korangi', label: 'Karachi Korangi' },
    { value: 'kashmore', label: 'Kashmore' },
    { value: 'khairpur', label: 'Khairpur' },
    { value: 'larkana', label: 'Larkana' },
    { value: 'matiari', label: 'Matiari' },
    { value: 'mirpur-khas', label: 'Mirpur Khas' },
    { value: 'naushahro-firoze', label: 'Naushahro Firoze' },
    { value: 'shaheed-benazirabad', label: 'Shaheed Benazirabad' },
    { value: 'qambar-shahdadkot', label: 'Qambar Shahdadkot' },
    { value: 'sanghar', label: 'Sanghar' },
    { value: 'shikarpur', label: 'Shikarpur' },
    { value: 'sukkur', label: 'Sukkur' },
    { value: 'tando-allahyar', label: 'Tando Allahyar' },
    { value: 'tando-muhammad-khan', label: 'Tando Muhammad Khan' },
    { value: 'tharparkar', label: 'Tharparkar' },
    { value: 'thatta', label: 'Thatta' },
    { value: 'umerkot', label: 'Umerkot' },
    { value: 'sujawal', label: 'Sujawal' }
  ],
  balochistan: [
    { value: 'awaran', label: 'Awaran' },
    { value: 'barkhan', label: 'Barkhan' },
    { value: 'chagai', label: 'Chagai' },
    { value: 'dera-bugti', label: 'Dera Bugti' },
    { value: 'gwadar', label: 'Gwadar' },
    { value: 'harnai', label: 'Harnai' },
    { value: 'jafarabad', label: 'Jafarabad' },
    { value: 'jhal-magsi', label: 'Jhal Magsi' },
    { value: 'kachhi', label: 'Kachhi' },
    { value: 'kalat', label: 'Kalat' },
    { value: 'kech', label: 'Kech' },
    { value: 'kharan', label: 'Kharan' },
    { value: 'khuzdar', label: 'Khuzdar' },
    { value: 'killa-abdullah', label: 'Killa Abdullah' },
    { value: 'killa-saifullah', label: 'Killa Saifullah' },
    { value: 'kohlu', label: 'Kohlu' },
    { value: 'lasbela', label: 'Lasbela' },
    { value: 'loralai', label: 'Loralai' },
    { value: 'mastung', label: 'Mastung' },
    { value: 'musakhel', label: 'Musakhel' },
    { value: 'nasirabad', label: 'Nasirabad' },
    { value: 'nushki', label: 'Nushki' },
    { value: 'panjgur', label: 'Panjgur' },
    { value: 'pishin', label: 'Pishin' },
    { value: 'quetta', label: 'Quetta' },
    { value: 'sherani', label: 'Sherani' },
    { value: 'sibi', label: 'Sibi' },
    { value: 'sohbatpur', label: 'Sohbatpur' },
    { value: 'washuk', label: 'Washuk' },
    { value: 'zhob', label: 'Zhob' },
    { value: 'ziarat', label: 'Ziarat' }
  ],
  khyber_pakhtunkhwa: [
    { value: 'abbottabad', label: 'Abbottabad' },
    { value: 'bajaur', label: 'Bajaur' },
    { value: 'bannu', label: 'Bannu' },
    { value: 'batagram', label: 'Batagram' },
    { value: 'buner', label: 'Buner' },
    { value: 'charsadda', label: 'Charsadda' },
    { value: 'chitral', label: 'Chitral' },
    { value: 'dera-ismail-khan', label: 'Dera Ismail Khan' },
    { value: 'hangu', label: 'Hangu' },
    { value: 'haripur', label: 'Haripur' },
    { value: 'karak', label: 'Karak' },
    { value: 'khyber', label: 'Khyber' },
    { value: 'kohat', label: 'Kohat' },
    { value: 'kurram', label: 'Kurram' },
    { value: 'lakki-marwat', label: 'Lakki Marwat' },
    { value: 'lower-dir', label: 'Lower Dir' },
    { value: 'malakand', label: 'Malakand' },
    { value: 'mansehra', label: 'Mansehra' },
    { value: 'mardan', label: 'Mardan' },
    { value: 'mohmand', label: 'Mohmand' },
    { value: 'north-waziristan', label: 'North Waziristan' },
    { value: 'nowshera', label: 'Nowshera' },
    { value: 'orakzai', label: 'Orakzai' },
    { value: 'peshawar', label: 'Peshawar' },
    { value: 'shangla', label: 'Shangla' },
    { value: 'south-waziristan', label: 'South Waziristan' },
    { value: 'swabi', label: 'Swabi' },
    { value: 'swat', label: 'Swat' },
    { value: 'tank', label: 'Tank' },
    { value: 'torghar', label: 'Torghar' },
    { value: 'upper-dir', label: 'Upper Dir' }
  ],
  gilgit: [
    { value: 'astore', label: 'Astore' },
    { value: 'ghanche', label: 'Ghanche' },
    { value: 'ghizer', label: 'Ghizer' },
    { value: 'gilgit', label: 'Gilgit' },
    { value: 'hunza', label: 'Hunza' },
    { value: 'kharmang', label: 'Kharmang' },
    { value: 'nagar', label: 'Nagar' },
    { value: 'shigar', label: 'Shigar' },
    { value: 'skardu', label: 'Skardu' },
    { value: 'tangir', label: 'Tangir' }
  ],
  kashmir: [
    { value: 'bhimber', label: 'Bhimber' },
    { value: 'hattian', label: 'Hattian' },
    { value: 'haveli', label: 'Haveli' },
    { value: 'kotli', label: 'Kotli' },
    { value: 'mirpur', label: 'Mirpur' },
    { value: 'muzaffarabad', label: 'Muzaffarabad' },
    { value: 'neelum', label: 'Neelum' },
    { value: 'poonch', label: 'Poonch' },
    { value: 'sudhnoti', label: 'Sudhnoti' },
    { value: 'bagh', label: 'Bagh' }
  ],
  islamabad: [{ value: 'islamabad', label: 'Islamabad' }]
};

export const getAllDistricts = () => {
  return Object.values(pakistanDistricts).flat();
};
